.github/workflows/ci.yml
=> fix: lint and test stage

.github/workflows/ci.yml, README.md
=> fix: coverage status

README.md
=> fix: readme test coverage status

.github/workflows/ci.yml, Dockerfile, cloudbuild.yaml
=> feat: setup Cloud Build deployment

.github/workflows/codeql-analysis.yml, cloudbuild.yaml
=> fix: update traffic to latest revision

cloudbuild.yaml
=> fix: update traffic to the latest revision

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, Dockerfile, cloudbuild.yaml
=> release: develop to main

graph/clinical/patient_email_template.go
=> chore: update email template UI and copy

.github/workflows/gitguardian.yaml
=> feat: integrate GitGuardian CI/CD security check

.github/workflows/deployment.yaml
=> feat: layout clinical testing community deployment

.github/workflows/ci.yml
=> chore: add schema validation cli command

.github/workflows/deployment.yaml
Push schema to registry only when we have a successful deployment
=> chore: add ci schema push to schema registry

deps.yaml
Depend on community onboarding and engagement services for ISC calls
=> chore: update inter-service api endpoints

go.sum, graph/entity.resolvers.go, graph/generated/federation.go, graph/generated/generated.go, graph/handlers_test.go, graph/schema/external.graphql
=> chore: fix tests for register user mutation

go.mod, go.sum, graph/entity.resolvers.go
Signed-off-by: Dumbledore <mathenge362@gmail.com>
=> chore: add Dummy type

pkg/clinical/usecases/fhir.go, pkg/clinical/usecases/patient.go
Make patient and fhir implementation agnostic i.e logic should be usecase specific
=> chore: port more fhir and patient usecases

pkg/clinical/usecases/fhir.go, pkg/clinical/usecases/patient.go
=> Restore methods

pkg/clinical/infrastructure/datastore/fhir/dataset.go, pkg/clinical/infrastructure/repository.go
=> chore: return fhir datastore layer implementation

pkg/clinical/application/dto/dto.go, pkg/clinical/infrastructure/services/onboarding/onboarding.go
=> Port onboarding isc impl

pkg/clinical/application/common/helpers/helpers.go, pkg/clinical/application/utils/patient_template.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/usecases/patient.go, pkg/clinical/usecases/patient_helpers.go
=> chore: implement patient usecases

pkg/clinical/infrastructure/datastore/fhir/dataset_test.go
=> chore: add fhir infrustructure/repository integration tests

pkg/clinical/usecases/mock/patient_mock.go, pkg/clinical/usecases/patient_unit_test.go
=> chore:add patient usecase unit tests

pkg/clinical/infrastructure/datastore/fhir/dataset_unit_test.go, pkg/clinical/infrastructure/datastore/firebase/firebase_unit_test.go, pkg/clinical/infrastructure/datastore/firebase/mock/firebase_extension_mock.go, pkg/clinical/infrastructure/mock/repository.go
=> Add repository mocks and unit tests

pkg/clinical/presentation/graph/healthpassport.resolvers.go, pkg/clinical/usecases/mock/patient_mock.go, pkg/clinical/usecases/patient.go
Implement missing graphql resolvers and usecases
=> feat: add missing usecases and implement graph resolvers

pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/presentation/rest/handlers_test.go, pkg/clinical/presentation/rest/rest.go, pkg/clinical/usecases/ocl/ocl.go, tests/acceptance_test.go, tests/config_test.go
Add GraphQFindPatientsByMSISDN
=> chore: add more critical acceptance testing

pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/presentation/graph/ocl.resolvers.go, pkg/clinical/usecases/config_test.go, pkg/clinical/usecases/fhir.go, pkg/clinical/usecases/mock/ocl_mock.go, pkg/clinical/usecases/ocl/ocl.go, pkg/clinical/usecases/patient.go, pkg/clinical/usecases/usecases.go, tests/acceptance_test.go
Improve usecase implementation and add acceptance tests
=> ref: refactor ocl implementation

pkg/clinical/usecases/fhir_unit_test.go, pkg/clinical/usecases/patient.go
Signed-off-by: Kathurima Kimathi <kathurimakimathi415@gmail.com>
=> chore:add fhir usecase unit tests

pkg/clinical/usecases/fhir_unit_test.go
=> chore: add fhir unit tests

.github/workflows/ci.yml, deps.yaml, go.mod, go.sum, pkg/clinical/infrastructure/datastore/fhir/dataset_test.go
=> chore: update firebase version

.github/workflows/deployment.yaml, .gitignore, Dockerfile
=> chore: add staging and prod deployment stages

.github/workflows/ci.yml, .github/workflows/deployment.yaml, deps.yaml, pkg/clinical/application/common/defaults.go, pkg/clinical/application/dto/pubsub.go, pkg/clinical/domain/mycarehub.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/mycarehub/service.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go
This MR leverages on pubsub to create a FHIR patient as soon as a
patient is registered on myCareHub
=> feat: register mycarehub client as FHIR patient

.github/workflows/deployment.yaml
=> chore: update github workflows `setup gcloud` command

.github/workflows/deployment.yaml
=> chore: update prod deployment environment

.github/workflows/deployment.yaml
=> chore: remove branch restriction on `deployment` workflow execution

pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go
=> fix: mycarehub isc initialization

pkg/clinical/application/dto/pubsub.go, pkg/clinical/domain/concept.go, pkg/clinical/domain/mycarehub.go, pkg/clinical/infrastructure/services/onboarding/onboarding.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go, pkg/clinical/usecases/fhir.go, pkg/clinical/usecases/fhir_integration_test.go
=> feat: create FHIR observations

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deployment.yaml, .github/workflows/gitguardian.yaml, pkg/clinical/application/dto/pubsub.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> feat: create FHIR allergy intolerance

go.mod, go.sum, pkg/clinical/application/dto/pubsub.go, pkg/clinical/domain/complex_types.go, pkg/clinical/domain/medication.go, pkg/clinical/domain/medication_statement.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/usecases/fhir.go
=> feat: create fhir medication statement

pkg/clinical/application/dto/pubsub.go, pkg/clinical/domain/concept.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> feat: create test result FHIR observation

pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> fix: store vital signs value as value strings

pkg/clinical/infrastructure/services/pubsub/service.go
=> chore: create organization pubsub topic

go.mod, go.sum, pkg/clinical/domain/complex_types.go, pkg/clinical/domain/medication.go, pkg/clinical/presentation/graph/fhir/Medication.graphql, pkg/clinical/presentation/graph/fhir/MedicationStatement.graphql, pkg/clinical/presentation/graph/generated/generated.go
=> chore: add graphql medication statement and medication types

.github/workflows/ci.yml, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/healthpassport.graphql, pkg/clinical/presentation/graph/healthpassport.resolvers.go, pkg/clinical/usecases/config_test.go, pkg/clinical/usecases/fhir.go, pkg/clinical/usecases/fhir_integration_test.go, tests/acceptance_test.go
=> feat: medication statement search

pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/healthpassport.graphql, pkg/clinical/presentation/graph/healthpassport.resolvers.go, pkg/clinical/usecases/patient.go, pkg/clinical/usecases/patient_integration_test.go, tests/acceptance_test.go
=> feat: simple health timeline

pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/usecases/patient.go
=> fix: create observations and patient timeline count

pkg/clinical/usecases/patient.go
=> fix: change medication statement in timeline

pkg/clinical/application/common/defaults.go, pkg/clinical/domain/patient.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/healthpassport.graphql, pkg/clinical/presentation/graph/healthpassport.resolvers.go, pkg/clinical/usecases/patient.go, pkg/clinical/usecases/patient_integration_test.go, tests/acceptance_test.go
=> feat: fetching medical data: allergies, regimen, weight, bmi, viral

.github/workflows/deployment.yaml, pkg/clinical/infrastructure/services/mycarehub/service.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go
Signed-off-by: Kathurima <kathurimakimathi415@gmail.com>
=> chore: add fhir organisation id to mycarehub facilities

.github/workflows/ci.yml, .github/workflows/deployment.yaml
=> chore: push schema to prod and staging schema registry

go.mod, go.sum, pkg/clinical/domain/timeline.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/healthpassport.graphql, pkg/clinical/presentation/graph/healthpassport.resolvers.go, pkg/clinical/usecases/patient.go, pkg/clinical/usecases/patient_integration_test.go, tests/acceptance_test.go
=> chore: paginated patient health timeline

pkg/clinical/presentation/config.go
Signed-off-by: Kathurima <kathurimakimathi415@gmail.com>
=> chore:delete patient isc endpoint

pkg/clinical/infrastructure/services/pubsub/subscriber.go
Signed-off-by: Kathurima <kathurimakimathi415@gmail.com>
=> chore: remove organization from allergy intolerance

pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> fix: fhir allergy intolerance payload composition

pkg/clinical/infrastructure/datastore/fhir/fhir.go
=> fix: purge observation resources before deleting patient resource

.github/workflows/demo.yaml
=> ci: deploy demo environment

deps.yaml
=> chore: add mycarehub demo to deps.yaml

.github/workflows/demo.yaml
=> ci: push schema to demo schema registry

go.mod, go.sum, pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> chore(deps): bump serverutils version

pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/usecases/clinical/patient.go
Signed-off-by: Kathurima <kathurimakimathi415@gmail.com>
=> chore: assorted chores

.github/workflows/ci.yml, .github/workflows/testing.yaml
=> fix(ci): update push to test schema registry workflow

pkg/clinical/infrastructure/datastore/fhir/fhir.go, pkg/clinical/usecases/clinical/patient.go
=> chore: remove sentry error reporting on some methods

.github/workflows/staging_multitenant.yaml
=> feat(ci): deploy multitenant staging environment

pkg/clinical/infrastructure/services/pubsub/subscriber.go
=> fix: assorted fixes

.github/workflows/staging_multitenant.yaml
Added the required secrets in yaml file
=> chore: fix multitenant staging deployment

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/fhir.go, pkg/clinical/usecases/clinical/patient.go
Separation of concerns led to the following:
-  Move patch and get patient logic to infrastructure layer
-  Move get episode of care login to infrastructure layer
=> refactor: move some logic into infra layers

.github/workflows/ci.yml, pkg/clinical/application/dto/output.go, pkg/clinical/domain/extension.go, pkg/clinical/domain/meta.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go
=> fix: remove dependency between pubsub and ocl usecase

pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/middleware.go, pkg/clinical/presentation/rest/middleware_test.go, tests/config_test.go
The middleware extracts specific headers from an HTTP request and add their values to the request context. The values passed will be used for filtering purposes
=> feat: introduce ID extraction middleware

pkg/clinical/application/common/testutils/testhelpers.go, pkg/clinical/application/extensions/extension.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/config_test.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go, pkg/clinical/usecases/config_test.go, pkg/clinical/usecases/ocl/ocl_test.go
=> chore: remove pubsub code from extension file

pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/middleware.go, pkg/clinical/presentation/rest/middleware_test.go, tests/config_test.go
=> feat: verify organisation provided in header exists

.golangci.yaml, pkg/clinical/application/common/defaults.go, pkg/clinical/application/common/helpers/helpers.go, pkg/clinical/application/common/helpers/isc_helper.go, pkg/clinical/application/common/testutils/testhelpers.go, pkg/clinical/domain/complex_types.go, pkg/clinical/domain/organization.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/mock/dataset_mock.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/helpers.go, pkg/clinical/infrastructure/services/mycarehub/service.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/config.go, pkg/clinical/usecases/clinical/fhir.go, pkg/clinical/usecases/config_test.go, pkg/clinical/usecases/ocl/ocl_test.go, server.go
linters include:
- unparam
- dupl
- errorlint
- bodyclose
- contextcheck
- gocritic
- nilerr
=> chore: update code to adhere to additional Go linting rules

.golangci.yaml, pkg/clinical/application/extensions/extension.go, pkg/clinical/domain/patient.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset_unit_test.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/subscriber.go, pkg/clinical/presentation/interactor/interactor.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/config_test.go, pkg/clinical/usecases/ocl/ocl.go, pkg/clinical/usecases/usecases.go
linters:
- ireturn
- importas
- repository interface improvement
=> chore: additional linters to improve code quality

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/usecases/clinical/mock/fhir_mock.go, pkg/clinical/usecases/clinical/mock/patient_mock.go
=> chore: remove redundant mocks

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/mock/dataset_mock.go
=> chore: unmarshal to a resource in create resource dataset method

.golangci.yaml, pkg/clinical/application/common/common.go, pkg/clinical/application/common/defaults.go, pkg/clinical/application/common/helpers/helpers.go, pkg/clinical/application/common/helpers/isc_helper.go, pkg/clinical/application/common/testutils/testhelpers.go, pkg/clinical/application/extensions/extension.go, pkg/clinical/application/utils/helpers.go, pkg/clinical/domain/complex_types.go, pkg/clinical/domain/models.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/helpers.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/infrastructure/services/mycarehub/service.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/graph/resolver.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/presentation/rest/middleware.go, pkg/clinical/usecases/clinical/fhir.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, server.go
=> chore: whitespace linter

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/mock/dataset_mock.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go
=> chore: add unit tests

pkg/clinical/application/extensions/mock/isc_mock.go, pkg/clinical/infrastructure/services/mycarehub/service_test.go
=> chore: add mycarehub service unit tests

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go
=> tests: fhir unit test

README.md, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go
=> tests: remove patient data test

pkg/clinical/application/common/testutils/testhelpers.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/mycarehub/mock/service_mock.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/presentation/config.go, pkg/clinical/usecases/clinical/fhir_test.go, pkg/clinical/usecases/clinical/mock/fhir_mock.go, pkg/clinical/usecases/clinical/mock/patient_mock.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/config_test.go
=> tests: add pubsub usecase tests

go.mod, go.sum, pkg/clinical/infrastructure/services/openconceptlab/service_test.go
=> test: ocl unit tests

pkg/clinical/domain/complex_types.go, pkg/clinical/domain/complex_types_test.go, pkg/clinical/domain/models_test.go, pkg/clinical/domain/patient_test.go
=> tests: add domain layer tests

go.mod, pkg/clinical/application/common/common_test.go, pkg/clinical/application/common/helpers/isc_helper_test.go, pkg/clinical/application/utils/helpers_test.go
=> chore: test application packages

pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/errors.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/application/utils/helpers.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/usecases/clinical/organization.go, pkg/clinical/usecases/clinical/organization_test.go, pkg/clinical/usecases/usecases.go
=> feat: api to create a tenant

.golangci.yaml, pkg/clinical/application/dto/input.go, pkg/clinical/application/utils/helpers.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/usecases/clinical/organization.go, pkg/clinical/usecases/clinical/organization_test.go, pkg/clinical/usecases/usecases.go
=> feat: add create facility API

Dockerfile
=> chore: Running gin in "release" mode for production

pkg/clinical/application/dto/output.go, pkg/clinical/application/extensions/extension.go, pkg/clinical/presentation/rest/middleware.go, pkg/clinical/usecases/clinical/utils.go
=> chore: facility request header

gqlgen.yml, pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/resolver.go, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/usecases.go
=> feat: create episode of care

pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql
=> chore: add observation models and graphql types

pkg/clinical/domain/episode_of_care.go, pkg/clinical/domain/patient.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/mock/dataset_mock.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/rest/middleware.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/encounter.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/clinical/mock/fhir_mock.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/utils.go, pkg/clinical/usecases/clinical/utils_test.go
=> feat: use tenant identifiers to filter resources in search

pkg/clinical/application/common/defaults.go, pkg/clinical/usecases/clinical/observation.go
=> chore: add terminology codes for vital signs

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: record patient height api

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: introduce record weight api

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: record respiratory rate api

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add api to record patient pulse rate

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add api to record patient blood pressure

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add api to record patient BMI

gqlgen.yml, pkg/clinical/application/common/common.go, pkg/clinical/application/common/defaults.go, pkg/clinical/application/common/helpers/helpers.go, pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/application/utils/helpers.go, pkg/clinical/domain/models.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/utils.go, pkg/clinical/usecases/usecases.go
=> feat: register patient

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/usecases.go
=> feat: episode of care retrieve and end

.github/workflows/ci.yml, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient's temperature entries

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient's blood pressure entries

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient height entries

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient's respiratory rate entries

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient pulse rate

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: retrieve patient's BMI entries

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: get patient weight

pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/allergy.go, pkg/clinical/usecases/clinical/allergy_test.go, pkg/clinical/usecases/clinical/condition.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, pkg/clinical/usecases/clinical/pubsub_test.go
=> chore: add allergy enums

pkg/clinical/application/dto/output.go, pkg/clinical/domain/concept.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/openconceptlab/mock/service_mock.go, pkg/clinical/infrastructure/services/openconceptlab/service.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/allergy.go, pkg/clinical/usecases/clinical/allergy_test.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/clinical/mock/allergy_mock.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/usecases.go
- searches for allegy by the provided name
=> feat: search allergy

pkg/clinical/application/dto/pagination.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/repository/mock/repository_mock.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/encounter.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/timeline.go, pkg/clinical/usecases/clinical/timeline_test.go, pkg/clinical/usecases/clinical/utils.go
=> chore: add pagination parameters

pkg/clinical/application/common/defaults.go, pkg/clinical/application/dto/enums.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/mycarehub/mock/service_mock.go, pkg/clinical/infrastructure/services/mycarehub/service.go, pkg/clinical/infrastructure/services/mycarehub/service_test.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/presentation/rest/handlers_test.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/usecases.go
- used to register the program created in MCH as a tenant in this service
=> feat: register clinical tenenant via pubsub

pkg/clinical/application/dto/pubsub.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/presentation/rest/handlers_test.go, pkg/clinical/usecases/clinical/mock/patient_mock.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/utils.go, pkg/clinical/usecases/usecases.go
=> chore: add facility id to records created via pubsub

pkg/clinical/application/dto/pubsub.go
=> fix: correct json tag naming

pkg/clinical/application/dto/enums.go, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go
=> chore: use uppercase enums

pkg/clinical/application/dto/pubsub.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/mycarehub/mock/service_mock.go, pkg/clinical/presentation/rest/handlers_test.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_test.go
=> fix: multitenant clinical patient registration and patient data creation

deps.yaml, pkg/clinical/infrastructure/services/mycarehub/service.go
=> fix: tenant creation when a program is created in mch

.github/workflows/demo.yaml, .github/workflows/testing.yaml
=> feat(ci): deploy `demo` environment to GKE

pkg/clinical/application/dto/encounter_output.go, pkg/clinical/application/dto/output.go, pkg/clinical/application/dto/pagination.go, pkg/clinical/domain/encounter.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/allergy.go, pkg/clinical/usecases/clinical/encounter.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/usecases.go
- paginates the list of encounters
=> chore: add encounters pagination

.github/workflows/staging.yaml
=> feat(ci): deploy `staging` environment to k8s

.github/workflows/prod.yaml, deploy/charts/clinical/templates/cluster_issuer.yaml
=> feat(ci): deploy prod environment to k8s

pkg/clinical/usecases/clinical/pubsub_helpers.go
=> chore: add patient ID in synced patient data

pkg/clinical/application/dto/observation_output.go, pkg/clinical/application/dto/output.go, pkg/clinical/usecases/clinical/pubsub_helpers.go
=> fix: synced medical data

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- this API is used to record patient's viral load
=> feat: record patient viral load

pkg/clinical/usecases/clinical/timeline.go
=> fix: health timeline display

.github/workflows/ci.yml, pkg/clinical/usecases/clinical/timeline.go
=> fix: medication statement display in timeline

.gitignore, pkg/clinical/usecases/clinical/observation.go
=> fix: get viral load

.github/workflows/staging_multitenant.yaml, pkg/clinical/presentation/config.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/types.graphql
=> feat(ci): deploy multitenant prod environment

pkg/clinical/usecases/clinical/pubsub.go
=> fix: update fhir patient id

pkg/clinical/application/common/defaults.go, pkg/clinical/application/dto/pubsub.go, pkg/clinical/infrastructure/infrastructure.go, pkg/clinical/infrastructure/services/pubsub/mock/service_mock.go, pkg/clinical/infrastructure/services/pubsub/publisher.go, pkg/clinical/infrastructure/services/pubsub/service.go, pkg/clinical/infrastructure/services/pubsub/service_test.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/handlers_test.go, pkg/clinical/usecases/clinical/allergy_test.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/clinical/media_test.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/organization_test.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/timeline_test.go, pkg/clinical/usecases/clinical/utils_test.go
=> chore: transition to pubsub from HTTP inter service calls

Dockerfile
=> chore: remove deps.yaml from dockerfile

pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go
=> chore: Remove phone number uniqueness check when registering patients

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/usecases.go
=> feat: Add patient deletion mutation

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go
=> fix: skip organisation resource when deleting patient data

gqlgen.yml, pkg/clinical/application/dto/input.go, pkg/clinical/domain/models.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/dataset.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhirdataset/mock/dataset_mock.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/utils.go, pkg/clinical/usecases/clinical/utils_test.go, pkg/clinical/usecases/usecases.go
=> feat: Add patient patch mutation

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> add muac missing vital

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add missing vital Spo2

pkg/clinical/application/dto/input.go, pkg/clinical/domain/complex_types.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/encounter.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care.go, pkg/clinical/usecases/usecases.go
=> feat: Add mutation to patch encounters

pkg/clinical/presentation/config.go
=> add advantage development origin url

pkg/clinical/presentation/config.go
=> add allowed headers

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> expose muac patient vital query

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> expose oxygen saturation query

pkg/clinical/application/dto/observation_output.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go
=> add timestamp to vitals

pkg/clinical/presentation/config.go
=> add advantage origin

pkg/clinical/application/dto/output.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/timeline.go
=> add timestamp to patient's timeline

gqlgen.yml, pkg/clinical/application/dto/condition_output.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/condition.go
- throws a nil pointer when on set date is not provided
=> fix: condition output

.github/workflows/ci.yml, pkg/clinical/application/common/helpers/helpers_test.go, pkg/clinical/application/dto/condition_output.go, pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/domain/complex_types_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/usecases/clinical/allergy_test.go, pkg/clinical/usecases/clinical/condition.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/clinical/media_test.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/timeline.go, pkg/clinical/usecases/clinical/timeline_test.go, pkg/clinical/usecases/clinical/utils_test.go, scripts/coverage.sh
=> add category input to Condition

pkg/clinical/application/dto/condition_output.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/condition.go
=> fix: fix listing of patient conditions

pkg/clinical/usecases/clinical/allergy.go, pkg/clinical/usecases/clinical/allergy_test.go
=> fix: check encounter finished status when creating allergies

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add record blood sugar api

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat: add api to fetch a patient's blood sugar observation

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> add diastolic blood pressure observation

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> adds fetching patient's diastolic blood pressure

pkg/clinical/application/dto/allergy_output.go, pkg/clinical/application/dto/composition_output.go, pkg/clinical/application/dto/observation_output.go, pkg/clinical/domain/composition.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/composition.go, pkg/clinical/usecases/clinical/composition_test.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/usecases.go
=> list patient's compositions

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/condition.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/usecases.go
=> query conditions with encounterID

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/composition.go, pkg/clinical/usecases/clinical/composition_test.go, pkg/clinical/usecases/usecases.go
=> query compositions with encounterID

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/condition.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/usecases.go
=> feat: add date filter on conditions

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/composition.go, pkg/clinical/usecases/clinical/composition_test.go, pkg/clinical/usecases/usecases.go
-adds date filter as a search param for compositions
=> feat: add date filter on composition

pkg/clinical/presentation/config.go
- https://review-empower.web.app
- https://review-advantage.web.app
=> chore: add empower urls to allowed origins

gqlgen.yml, pkg/clinical/application/common/defaults.go, pkg/clinical/application/dto/composition_output.go, pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/domain/composition.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/composition.go, pkg/clinical/usecases/clinical/composition_test.go, pkg/clinical/usecases/usecases.go
=> feat: append notes to composition section

pkg/clinical/application/common/helpers/helpers.go, pkg/clinical/domain/complex_types.go, pkg/clinical/domain/observation.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/allergy_test.go, pkg/clinical/usecases/clinical/composition_test.go, pkg/clinical/usecases/clinical/condition.go, pkg/clinical/usecases/clinical/condition_test.go, pkg/clinical/usecases/clinical/encounter_test.go, pkg/clinical/usecases/clinical/episode_of_care_test.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/clinical/patient.go, pkg/clinical/usecases/clinical/patient_unit_test.go, pkg/clinical/usecases/clinical/pubsub.go, pkg/clinical/usecases/clinical/pubsub_helpers.go, pkg/clinical/usecases/clinical/pubsub_test.go, pkg/clinical/usecases/clinical/timeline.go, pkg/clinical/usecases/clinical/timeline_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's height entries
=> feat: patch patient height observation

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's weight entries
=> feat: patch patient weight observation

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's BMI entries
=> feat: patch patient BMI observation

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's diastolic & systolic blood pressure entries
=> feat: patch patient diastolic & systolic blood pressure observations

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's respiration rate entries
=> feat: patch patient respiration rate observation

pkg/clinical/domain/questionnaire.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/config.go, pkg/clinical/presentation/rest/handlers.go, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/questionnaire.go, pkg/clinical/usecases/clinical/questionnaire_test.go, pkg/clinical/usecases/usecases.go
=> feat: [OHE-472] load questionnaire to fhir registry

pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/application/dto/output.go, pkg/clinical/domain/consent.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/consent.go, pkg/clinical/usecases/clinical/consent_test.go, pkg/clinical/usecases/usecases.go
=> feat[OHE-475]: add record consent

pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go
- This change adds tests for FHIR Observation & Composition resources
=> test: add observation & composition FHIR tests

pkg/clinical/application/common/defaults.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
=> feat[OHE-466]: add record colposcopy

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's oxygen saturation entries
=> feat: patch patient oxygen saturation observation

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's pulse rate entries
=> feat: patch patient pulse rate observation

gqlgen.yml, pkg/clinical/application/dto/enums.go, pkg/clinical/application/dto/input.go, pkg/clinical/domain/questionnaire_response.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/fhir_unit_test.go, pkg/clinical/infrastructure/datastore/cloudhealthcare/mock/fhir_mock.go, pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/enums.graphql, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/presentation/graph/inputs.graphql, pkg/clinical/presentation/graph/types.graphql, pkg/clinical/repository/repository.go, pkg/clinical/usecases/clinical/questionnaire_response.go, pkg/clinical/usecases/clinical/questionnaire_response_test.go, pkg/clinical/usecases/usecases.go
=> feat[OHE-464]: add questionnaire response

pkg/clinical/presentation/graph/clinical.graphql, pkg/clinical/presentation/graph/clinical.resolvers.go, pkg/clinical/presentation/graph/generated/generated.go, pkg/clinical/usecases/clinical/observation.go, pkg/clinical/usecases/clinical/observation_test.go, pkg/clinical/usecases/usecases.go
- This patches patient's muac entries
=> feat: patch patient muac observation
